"""added 2 new fields in User model

Revision ID: 77aea43ace0c
Revises: 0dc2543b322c
Create Date: 2018-07-22 19:27:39.314446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77aea43ace0c'
down_revision = '0dc2543b322c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
